part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const SPLASH = _Paths.SPLASH;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const OTP_VERIFICATION = _Paths.OTP_VERIFICATION;
  static const REGISTER_ROLE_CHOOSER = _Paths.REGISTER_ROLE_CHOOSER;
  static const REGISTER_FARMER = _Paths.REGISTER_FARMER;
  static const REGISTER_INVESTOR = _Paths.REGISTER_INVESTOR;
  static const REGISTER_EXPERT = _Paths.REGISTER_EXPERT;
  static const MAIN_NAVIGATION = _Paths.MAIN_NAVIGATION;
  static const HOME_DASHBOARD = _Paths.HOME_DASHBOARD;
  static const KYC_FORM = _Paths.KYC_FORM;
  static const STORE_HOME = _Paths.STORE_HOME;
  static const PRODUCT_SEARCH = _Paths.PRODUCT_SEARCH;
  static const PRODUCT_DETAIL = _Paths.PRODUCT_DETAIL;
  static const PRODUCT_REVIEWS = _Paths.PRODUCT_REVIEWS;
  static const CART = _Paths.CART;
  static const CHECKOUT_ADDRESS = _Paths.CHECKOUT_ADDRESS;
  static const CHECKOUT_PAYMENT = _Paths.CHECKOUT_PAYMENT;
  static const ORDER_CONFIRMATION = _Paths.ORDER_CONFIRMATION;
  static const ORDER_HISTORY = _Paths.ORDER_HISTORY;
  static const ORDER_TRACKING_DETAIL = _Paths.ORDER_TRACKING_DETAIL;
  static const CLINIC_HOME = _Paths.CLINIC_HOME;
  static const CLINIC_EXPERT_LIST = _Paths.CLINIC_EXPERT_LIST;
  static const CLINIC_EXPERT_PROFILE = _Paths.CLINIC_EXPERT_PROFILE;
  static const CONSULTATION_CHAT_ROOM = _Paths.CONSULTATION_CHAT_ROOM;
  static const CONSULTATION_VIDEO_CALL = _Paths.CONSULTATION_VIDEO_CALL;
  static const EXPERT_DASHBOARD = _Paths.EXPERT_DASHBOARD;
  static const EXPERT_AVAILABILITY_SETTINGS =
      _Paths.EXPERT_AVAILABILITY_SETTINGS;
  static const EXPERT_PAYOUT = _Paths.EXPERT_PAYOUT;
  static const CLINIC_AI_SCAN = _Paths.CLINIC_AI_SCAN;
  static const CLINIC_DIGITAL_LIBRARY = _Paths.CLINIC_DIGITAL_LIBRARY;
  static const CLINIC_LIBRARY_READER = _Paths.CLINIC_LIBRARY_READER;
  static const TENDER_MARKETPLACE = _Paths.TENDER_MARKETPLACE;
  static const TENDER_CREATE_REQUEST = _Paths.TENDER_CREATE_REQUEST;
  static const TENDER_DETAIL = _Paths.TENDER_DETAIL;
  static const TENDER_SUBMIT_OFFER = _Paths.TENDER_SUBMIT_OFFER;
  static const TENDER_MY_OFFERS_LIST = _Paths.TENDER_MY_OFFERS_LIST;
  static const PROFILE_MAIN = _Paths.PROFILE_MAIN;
  static const WALLET_MAIN = _Paths.WALLET_MAIN;
  static const WALLET_HISTORY = _Paths.WALLET_HISTORY;
  static const WALLET_TOP_UP = _Paths.WALLET_TOP_UP;
  static const WALLET_WITHDRAW = _Paths.WALLET_WITHDRAW;
  static const MANAGE_BANK_ACCOUNTS = _Paths.MANAGE_BANK_ACCOUNTS;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const FARMER_MANAGE_ASSETS = _Paths.FARMER_MANAGE_ASSETS;
  static const FARMER_ADD_ASSET_FORM = _Paths.FARMER_ADD_ASSET_FORM;
  static const FARMER_ASSET_DETAIL = _Paths.FARMER_ASSET_DETAIL;
  static const FARMER_APPLY_FUNDING_FORM = _Paths.FARMER_APPLY_FUNDING_FORM;
  static const FARMER_MY_PROJECTS_LIST = _Paths.FARMER_MY_PROJECTS_LIST;
  static const INVESTOR_FUNDING_MARKETPLACE =
      _Paths.INVESTOR_FUNDING_MARKETPLACE;
  static const INVESTOR_PROJECT_DETAIL = _Paths.INVESTOR_PROJECT_DETAIL;
  static const INVESTOR_INVEST_FORM = _Paths.INVESTOR_INVEST_FORM;
  static const INVESTOR_PORTFOLIO = _Paths.INVESTOR_PORTFOLIO;
  static const INVESTOR_PORTFOLIO_DETAIL = _Paths.INVESTOR_PORTFOLIO_DETAIL;
  static const CREATE_NEW_PASSWORD = _Paths.CREATE_NEW_PASSWORD;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const SPLASH = '/splash';
  static const ONBOARDING = '/onboarding';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const OTP_VERIFICATION = '/otp-verification';
  static const REGISTER_ROLE_CHOOSER = '/register-role-chooser';
  static const REGISTER_FARMER = '/register-farmer';
  static const REGISTER_INVESTOR = '/register-investor';
  static const REGISTER_EXPERT = '/register-expert';
  static const MAIN_NAVIGATION = '/main-navigation';
  static const HOME_DASHBOARD = '/home-dashboard';
  static const KYC_FORM = '/kyc-form';
  static const STORE_HOME = '/store-home';
  static const PRODUCT_SEARCH = '/product-search';
  static const PRODUCT_DETAIL = '/product-detail';
  static const PRODUCT_REVIEWS = '/product-reviews';
  static const CART = '/cart';
  static const CHECKOUT_ADDRESS = '/checkout-address';
  static const CHECKOUT_PAYMENT = '/checkout-payment';
  static const ORDER_CONFIRMATION = '/order-confirmation';
  static const ORDER_HISTORY = '/order-history';
  static const ORDER_TRACKING_DETAIL = '/order-tracking-detail';
  static const CLINIC_HOME = '/clinic-home';
  static const CLINIC_EXPERT_LIST = '/clinic-expert-list';
  static const CLINIC_EXPERT_PROFILE = '/clinic-expert-profile';
  static const CONSULTATION_CHAT_ROOM = '/consultation-chat-room';
  static const CONSULTATION_VIDEO_CALL = '/consultation-video-call';
  static const EXPERT_DASHBOARD = '/expert-dashboard';
  static const EXPERT_AVAILABILITY_SETTINGS = '/expert-availability-settings';
  static const EXPERT_PAYOUT = '/expert-payout';
  static const CLINIC_AI_SCAN = '/clinic-ai-scan';
  static const CLINIC_DIGITAL_LIBRARY = '/clinic-digital-library';
  static const CLINIC_LIBRARY_READER = '/clinic-library-reader';
  static const TENDER_MARKETPLACE = '/tender-marketplace';
  static const TENDER_CREATE_REQUEST = '/tender-create-request';
  static const TENDER_DETAIL = '/tender-detail';
  static const TENDER_SUBMIT_OFFER = '/tender-submit-offer';
  static const TENDER_MY_OFFERS_LIST = '/tender-my-offers-list';
  static const PROFILE_MAIN = '/profile-main';
  static const WALLET_MAIN = '/wallet-main';
  static const WALLET_HISTORY = '/wallet-history';
  static const WALLET_TOP_UP = '/wallet-top-up';
  static const WALLET_WITHDRAW = '/wallet-withdraw';
  static const MANAGE_BANK_ACCOUNTS = '/manage-bank-accounts';
  static const CHANGE_PASSWORD = '/change-password';
  static const FARMER_MANAGE_ASSETS = '/farmer-manage-assets';
  static const FARMER_ADD_ASSET_FORM = '/farmer-add-asset-form';
  static const FARMER_ASSET_DETAIL = '/farmer-asset-detail';
  static const FARMER_APPLY_FUNDING_FORM = '/farmer-apply-funding-form';
  static const FARMER_MY_PROJECTS_LIST = '/farmer-my-projects-list';
  static const INVESTOR_FUNDING_MARKETPLACE = '/investor-funding-marketplace';
  static const INVESTOR_PROJECT_DETAIL = '/investor-project-detail';
  static const INVESTOR_INVEST_FORM = '/investor-invest-form';
  static const INVESTOR_PORTFOLIO = '/investor-portfolio';
  static const INVESTOR_PORTFOLIO_DETAIL = '/investor-portfolio-detail';
  static const CREATE_NEW_PASSWORD = '/create-new-password';
}
